### PR TITLE
add L-M solver & GLOG

### PR DESCRIPTION
**Pull request by suyunzzz**
I0107 21:46:18.242332 426856 pnp_benchmark.cpp:129] Method: LM, **_rotation error 0.215836 deg_**, **_translation error 0.166152_**

### CODE REVIEW

**Comment by qiaozhijian** [comment]
Thank you very much! By the way, have you tested it on your dataset and compare it with OpenCV?

**Comment by suyunzzz** [comment]
> Thank you very much! By the way, have you tested it on your dataset and compare it with OpenCV?

no, the param to compute lambda need fine-tuning

**Comment by qiaozhijian** [comment]
> > Thank you very much! By the way, have you tested it on your dataset and compare it with OpenCV?
> 
> no, the param to compute lambda need fine-tuning

Using simulation dataset is ok. Thank you for PR.

**Comment by qiaozhijian** [comment]
No, I find I test these algorithms on simulation dataset. Never mind, it's just for learning. We still use OpenCV 🙂
________________________________
发件人: suyunzzz ***@***.***>
发送时间: 2024年1月10日 16:10
收件人: qiaozhijian/PnP-Solver ***@***.***>
抄送: QIAO Zhijian ***@***.***>; State change ***@***.***>
主题: Re: [qiaozhijian/PnP-Solver] add L-M solver & GLOG (PR #1)


Thank you very much! By the way, have you tested it on your dataset and compare it with OpenCV?

no, the param to compute lambda need fine-tuning

**Pull request merged**
